# Compose configuration file for the lldap service
#
# This file is derived from the example code of the following official configuration:
# https://github.com/lldap/lldap?tab=readme-ov-file#with-docker
#
# Copyright 2025 lldap project contributors <https://github.com/lldap/lldap/commits/0baee7a/README.md>
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

volumes:
  lldap_data:
    driver: local

services:
  lldap:
    image: lldap/lldap:stable
    ports:
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    env_file:
      - .env
